# Generated by Django 4.2 on 2023-08-15 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyageapp', '0002_tourguide'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='teampic')),
                ('desc', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Tourguide',
        ),
    ]
